services:
  - type: web
    name: previewhub
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn server.app:app --bind 0.0.0.0:$PORT --worker-class gevent --workers 1 --timeout 600 --graceful-timeout 30 --keep-alive 75
    autoDeploy: true
